In [2]:
#Bản nhập từ file txt
#Bài 1
import numpy as np
from collections import deque

# Đọc danh sách cạnh từ file txt
def read_edges_from_file(file_path):
    edges = []
    with open(file_path, 'r') as file:
        for line in file:
            u, v = map(int, line.strip().split())
            edges.append((u, v))
    return edges

# 1. Sử dụng ma trận kề để biểu diễn đồ thị
def create_adj_matrix(edges, num_vertices):
    adj_matrix = np.zeros((num_vertices + 1, num_vertices + 1), dtype=int)
    for u, v in edges:
        adj_matrix[u][v] = 1
        adj_matrix[v][u] = 1
    return adj_matrix

# 2. Sử dụng danh sách cạnh để biểu diễn đồ thị
def create_adj_list(edges, num_vertices):
    adj_list = {i: [] for i in range(1, num_vertices + 1)}
    for u, v in edges:
        adj_list[u].append(v)
        adj_list[v].append(u)
    return adj_list

# 3. Hiện thực lại giải thuật BFS – Duyệt đồ thị từ đỉnh 5
def bfs(adj_list, start):
    visited = [False] * (len(adj_list) + 1)
    queue = deque([start])
    visited[start] = True
    order = []

    while queue:
        vertex = queue.popleft()
        order.append(vertex)

        for neighbor in adj_list[vertex]:
            if not visited[neighbor]:
                queue.append(neighbor)
                visited[neighbor] = True

    return order

# 4. Hiện thực lại giải thuật DFS – Duyệt đồ thị từ đỉnh 7
def dfs(adj_list, start):
    visited = [False] * (len(adj_list) + 1)
    stack = [start]
    order = []

    while stack:
        vertex = stack.pop()
        if not visited[vertex]:
            visited[vertex] = True
            order.append(vertex)
            for neighbor in adj_list[vertex]:
                if not visited[neighbor]:
                    stack.append(neighbor)

    return order

# Định nghĩa file chứa danh sách cạnh
file_path = 'edges.txt'

# Đọc danh sách cạnh từ file
edges = read_edges_from_file(file_path)
num_vertices = 10

# Tạo ma trận kề
adj_matrix = create_adj_matrix(edges, num_vertices)
print("Ma trận kề:")
print(adj_matrix)

# Tạo danh sách cạnh
adj_list = create_adj_list(edges, num_vertices)
print("\nDanh sách cạnh:")
for key, value in adj_list.items():
    print(f"{key}: {value}")

# Duyệt đồ thị bằng BFS từ đỉnh 5
print("\nBFS từ đỉnh 5:")
print(bfs(adj_list, 5))

# Duyệt đồ thị bằng DFS từ đỉnh 7
print("\nDFS từ đỉnh 7:")
print(dfs(adj_list, 7))


Ma trận kề:
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 1 0 0 0 1 0 0]
 [0 1 0 1 0 0 0 0 1 0 1]
 [0 1 1 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 1]
 [0 0 1 0 0 1 1 0 0 0 0]
 [0 0 1 0 1 1 0 0 1 0 0]]

Danh sách cạnh:
1: [4, 5]
2: [5, 9, 10]
3: [4, 8]
4: [1, 3, 8, 10]
5: [1, 2, 9, 10]
6: [7, 9]
7: [6]
8: [3, 4, 10]
9: [2, 5, 6]
10: [2, 4, 5, 8]

BFS từ đỉnh 5:
[5, 1, 2, 9, 10, 4, 6, 8, 3, 7]

DFS từ đỉnh 7:
[7, 6, 9, 5, 10, 8, 4, 3, 1, 2]


In [3]:
#Bài 2
import numpy as np
from collections import deque

# Đọc danh sách cạnh từ file txt
def read_edges_from_file(file_path):
    edges = []
    with open(file_path, 'r') as file:
        for line in file:
            u, v = map(int, line.strip().split())
            edges.append((u, v))
    return edges

# 5. Sử dụng ma trận kề để biểu diễn đồ thị
def create_adj_matrix(edges, num_vertices):
    adj_matrix = np.zeros((num_vertices + 1, num_vertices + 1), dtype=int)
    for u, v in edges:
        adj_matrix[u][v] = 1
        adj_matrix[v][u] = 1
    return adj_matrix

# 6. Sử dụng danh sách cạnh để biểu diễn đồ thị
def create_adj_list(edges, num_vertices):
    adj_list = {i: [] for i in range(1, num_vertices + 1)}
    for u, v in edges:
        adj_list[u].append(v)
        adj_list[v].append(u)
    return adj_list

# 7. Hiện thực lại giải thuật BFS – Duyệt đồ thị từ đỉnh 1
def bfs(adj_list, start):
    visited = [False] * (len(adj_list) + 1)
    queue = deque([start])
    visited[start] = True
    order = []

    while queue:
        vertex = queue.popleft()
        order.append(vertex)

        for neighbor in adj_list[vertex]:
            if not visited[neighbor]:
                queue.append(neighbor)
                visited[neighbor] = True

    return order

# 8. Hiện thực lại giải thuật DFS – Duyệt đồ thị từ đỉnh 4
def dfs(adj_list, start):
    visited = [False] * (len(adj_list) + 1)
    stack = [start]
    order = []

    while stack:
        vertex = stack.pop()
        if not visited[vertex]:
            visited[vertex] = True
            order.append(vertex)
            for neighbor in adj_list[vertex]:
                if not visited[neighbor]:
                    stack.append(neighbor)

    return order

# Định nghĩa file chứa danh sách cạnh
file_path = 'edges1.txt'

# Đọc danh sách cạnh từ file
edges = read_edges_from_file(file_path)
num_vertices = 7

# Tạo ma trận kề
adj_matrix = create_adj_matrix(edges, num_vertices)
print("Ma trận kề:")
print(adj_matrix)

# Tạo danh sách cạnh
adj_list = create_adj_list(edges, num_vertices)
print("\nDanh sách cạnh:")
for key, value in adj_list.items():
    print(f"{key}: {value}")

# Duyệt đồ thị bằng BFS từ đỉnh 1
print("\nBFS từ đỉnh 1:")
print(bfs(adj_list, 1))

# Duyệt đồ thị bằng DFS từ đỉnh 4
print("\nDFS từ đỉnh 4:")
print(dfs(adj_list, 4))


Ma trận kề:
[[0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 1 0 0 1 1 0 0]
 [0 1 0 0 1 0 0 0]
 [0 0 1 1 0 1 1 1]
 [0 0 1 0 1 0 0 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 1 0]]

Danh sách cạnh:
1: [2, 3]
2: [1, 5, 4]
3: [1, 4]
4: [3, 2, 5, 6, 7]
5: [2, 4, 7]
6: [4, 7]
7: [4, 5, 6]

BFS từ đỉnh 1:
[1, 2, 3, 5, 4, 7, 6]

DFS từ đỉnh 4:
[4, 7, 6, 5, 2, 1, 3]
