In [1]:
#Bài 1
import numpy as np
from collections import deque

# 1. Sử dụng ma trận kề để biểu diễn đồ thị
# Ma trận kề
adj_matrix = np.zeros((11, 11), dtype=int)

edges = [
    (1, 5), (1, 6), (2, 9), (2, 10), (3, 8), (3, 4),
    (4, 8), (4, 10), (5, 9), (6, 9), (6, 7), (8, 10)
]

for u, v in edges:
    adj_matrix[u][v] = 1
    adj_matrix[v][u] = 1

print("Ma trận kề:")
print(adj_matrix)

# 2. Sử dụng danh sách cạnh để biểu diễn đồ thị
# Danh sách cạnh
adj_list = {i: [] for i in range(1, 11)}

for u, v in edges:
    adj_list[u].append(v)
    adj_list[v].append(u)

print("\nDanh sách cạnh:")
for key, value in adj_list.items():
    print(f"{key}: {value}")

# 3. Hiện thực lại giải thuật BFS – Duyệt đồ thị từ đỉnh 5
def bfs(start):
    visited = [False] * 11
    queue = deque([start])
    visited[start] = True
    order = []

    while queue:
        vertex = queue.popleft()
        order.append(vertex)

        for neighbor in adj_list[vertex]:
            if not visited[neighbor]:
                queue.append(neighbor)
                visited[neighbor] = True

    return order

print("\nBFS từ đỉnh 5:")
print(bfs(5))

# 4. Hiện thực lại giải thuật DFS – Duyệt đồ thị từ đỉnh 7
def dfs(start):
    visited = [False] * 11
    stack = [start]
    order = []

    while stack:
        vertex = stack.pop()
        if not visited[vertex]:
            visited[vertex] = True
            order.append(vertex)
            for neighbor in adj_list[vertex]:
                if not visited[neighbor]:
                    stack.append(neighbor)

    return order

print("\nDFS từ đỉnh 7:")
print(dfs(7))


Ma trận kề:
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 1]
 [0 0 1 0 0 1 1 0 0 0 0]
 [0 0 1 0 1 0 0 0 1 0 0]]

Danh sách cạnh:
1: [5, 6]
2: [9, 10]
3: [8, 4]
4: [3, 8, 10]
5: [1, 9]
6: [1, 9, 7]
7: [6]
8: [3, 4, 10]
9: [2, 5, 6]
10: [2, 4, 8]

BFS từ đỉnh 5:
[5, 1, 9, 6, 2, 7, 10, 4, 8, 3]

DFS từ đỉnh 7:
[7, 6, 9, 5, 1, 2, 10, 8, 4, 3]


In [2]:
#Bài 2
import numpy as np
from collections import deque

# Định nghĩa các cạnh của đồ thị
edges = [
    (1, 2), (1, 3), (2, 5), (3, 4), (4, 2), (4, 5), (4, 6), (4, 7), (5, 7), (6, 7)
]

# 5. Sử dụng ma trận kề để biểu diễn đồ thị
num_vertices = 7  # Số đỉnh của đồ thị
adj_matrix = np.zeros((num_vertices + 1, num_vertices + 1), dtype=int)

for u, v in edges:
    adj_matrix[u][v] = 1

print("Ma trận kề:")
print(adj_matrix)

# 6. Sử dụng danh sách cạnh để biểu diễn đồ thị
adj_list = {i: [] for i in range(1, num_vertices + 1)}

for u, v in edges:
    adj_list[u].append(v)

print("\nDanh sách cạnh:")
for key, value in adj_list.items():
    print(f"{key}: {value}")

# 7. Hiện thực lại giải thuật BFS – Duyệt đồ thị từ đỉnh 1
def bfs(start):
    visited = [False] * (num_vertices + 1)
    queue = deque([start])
    visited[start] = True
    order = []

    while queue:
        vertex = queue.popleft()
        order.append(vertex)

        for neighbor in adj_list[vertex]:
            if not visited[neighbor]:
                queue.append(neighbor)
                visited[neighbor] = True

    return order

print("\nBFS từ đỉnh 1:")
print(bfs(1))

# 8. Hiện thực lại giải thuật DFS – Duyệt đồ thị từ đỉnh 4
def dfs(start):
    visited = [False] * (num_vertices + 1)
    stack = [start]
    order = []

    while stack:
        vertex = stack.pop()
        if not visited[vertex]:
            visited[vertex] = True
            order.append(vertex)
            for neighbor in adj_list[vertex]:
                if not visited[neighbor]:
                    stack.append(neighbor)

    return order

print("\nDFS từ đỉnh 4:")
print(dfs(4))


Ma trận kề:
[[0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 1 1 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]]

Danh sách cạnh:
1: [2, 3]
2: [5]
3: [4]
4: [2, 5, 6, 7]
5: [7]
6: [7]
7: []

BFS từ đỉnh 1:
[1, 2, 3, 5, 4, 7, 6]

DFS từ đỉnh 4:
[4, 7, 6, 5, 2]
