In [ ]:
print("Bài 1")

In [ ]:
n=int(input("Nhập số nguyên n: "))
if n > 0:
    tong=0
    for i in range(n):
        i+=1
        tong+=i
    print("Tổng dãy số từ 1 đến",n,"là:",tong)

In [ ]:
print("Bài 2")

In [ ]:
n=int(input("Nhập số nguyên n: "))
total1=0
total2=0
for i in range(1, 1001):
    if i%2==1: 
        total1=total1+i
    if i%2==0: 
        total2=total2-i  
total = total1 + total2 
print("Kết quả là:",total)


In [ ]:
print("Bài 3")

In [ ]:
year=int(input("Nhập năm:"))
if (year % 4 == 0) and (year % 100 != 0) or (year % 400 == 0): 
    print("Năm",year,"là năm nhuận") 
else: 
    print("Năm",year,"không là năm nhuận")



In [ ]:
print("Bài 4")

In [ ]:
c=int(input("Nhập độ C:"))
f=c*(9/5)+32 
print("Độ F là:",f)

In [ ]:
print("Bài 5 và Bài 6") 

In [ ]:
n=int(input("Nhập số nguyên n:"))
digits=[]    
while n != 0:
    digit = n % 10 
    digits.append(digit)  
    n = n // 10
digits.reverse()
print("Thứ tự xuôi:",digits)

digits.reverse()
print("Thứ tự ngược lại:", digits)


In [ ]:
print("Bài 7")

In [ ]:
binary=str(input("Nhập dãy nhị phân:"))
decimal=int(input("Nhập số thập phân:"))

def bin_to_dec(daynhiphan):
    dec=0
    bac=0
    for i in reversed(daynhiphan):
        dec+=int(i)*(2**bac)
        bac+=1
    return dec

def dec_to_bin(n):
    if n==0:
        return "0"
    bin=""
    while n > 0:
        bin=str(n%2)+bin
        n//=2
    return bin
        
result1=bin_to_dec(binary)
result2=dec_to_bin(decimal)

print("Số thập phân của dãy nhị phân trên là:",result1)
print("Dãy nhị phân của số thập phân trên là:",result2)

In [ ]:
print("Bài 8")

In [ ]:
a=int(input("Nhập số a:"))
b=int(input("Nhập số b:"))
c=int(input("Nhập số c:"))
print(f"Phương trình bậc 2 là: {a}x^2 + {b}x + {c} = 0")

delta=(b**2)-(4*a*c)

if delta<0:
    print("Phương trình vô nghiệm")
if delta==0:
    nghiemkep=(-1*b)/(2*a)
    print(f"Phương trình có nghiệm kép: a = {nghiemkep}")
if delta>0:
    nghiem1=(-1*(b-(delta**(1/2))))/(2*a)
    nghiem2=(-1*(b+(delta**(1/2))))/(2*a)
    print(f"Phương trình có hai nghiệm phân biệt: a={nghiem1} hoặc b={nghiem2}")


In [1]:
print("Bài 9")

Bài 9


In [5]:
def TimSoNguyenTo(n):
    i = 2
    SoNguyenTo = []
    while i <= n:
        if n % i == 0:
            SoNguyenTo.append(i)
            n //= i
        else:
            i += 1
    return SoNguyenTo

n = int(input("Nhập số nguyên dương n: "))
if n > 0:
    answer = TimSoNguyenTo(n)
    print("Số nguyên tố của", n, "là:", answer)

Các thừa số nguyên tố của 5 là: [5]


In [6]:
print("Bài 10")

Bài 10


In [4]:
def XacDinhNgayCuaThang(month, year):
    if month in [1, 3, 5, 7, 8, 10, 12]:
        return 31
    if month in [4, 6, 9, 11]:
        return 30
    if month == 2:
        if (year % 4 == 0) and (year % 100 != 0) or (year % 400 == 0): 
            return 29
        else:
            return 28
    return 0

def NgayHomTruoc(day, month, year):
    if day > 1:
        return day - 1, month, year
    else:
        if month == 1:
            return 31, 12, year - 1
        else:
            month -= 1
            day = XacDinhNgayCuaThang(month, year)
            return day, month, year

def NgayHomSau(day, month, year):
    if day < XacDinhNgayCuaThang(month, year):
        return day + 1, month, year
    else:
        if month == 12:
            return 1, 1, year + 1
        else:
            month += 1
            return 1, month, year


date = input("Nhập vào ngày tháng năm: ")
print(f"Ngày đã nhập:",date)
day, month, year = map(int, date.split('-'))


pday, pmonth, pyear = NgayHomTruoc(day, month, year)
nday, nmonth, nyear = NgayHomSau(day, month, year)


print(f"Ngày hôm trước: {pday:02}-{pmonth:02}-{pyear}")
print(f"Ngày hôm sau: {nday:02}-{nmonth:02}-{nyear}")


Ngày đã nhập: 1-1-2019
Ngày hôm trước: 31-12-2018
Ngày hôm sau: 02-01-2019


In [9]:
print("Bài 11")

Bài 11


In [6]:
DaySo = input("Nhập một danh sách các số nguyên, cách nhau bằng dấu cách: ")
PhanTu = list(map(int, DaySo.split(',')))

TongDaySo = 0
DemSoChan = 0
DemSoHaiChuSo = 0

for so in PhanTu:
    TongDaySo += so
    if so % 2 == 0:
        DemSoChan += 1
    if abs(so) in range (10,100):
        DemSoHaiChuSo += 1

print("Dãy số vừa nhập là:",DaySo)
print("Tổng các số vừa nhập:",TongDaySo)
print("Số lượng các số chẵn:",DemSoChan)
print("Số lượng các số có 2 chữ số:",DemSoHaiChuSo)





Dãy số vừa nhập là: 10,1,5,34,100
Tổng các số vừa nhập: 150
Số lượng các số chẵn: 3
Số lượng các số có 2 chữ số: 2


In [1]:
print("Bài 12")

Bài 12


In [1]:
def hoan_vi(a, b):
    temp = a
    a = b
    b = temp
    return a, b

def interchange_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(i + 1, n):
            if arr[i] > arr[j]:
                arr[i], arr[j] = hoan_vi(arr[i], arr[j])

def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = hoan_vi(arr[j], arr[j + 1])

# Nhập danh sách các số nguyên từ người dùng
DaySo = input("Nhập một danh sách các số nguyên: ")
PhanTu = list(map(int, DaySo.split(',')))

# Tạo bản sao của danh sách để sắp xếp bằng các thuật toán khác nhau
PhanTu_interchange = PhanTu.copy()
PhanTu_bubble = PhanTu.copy()

# Sắp xếp bằng Interchange Sort
interchange_sort(PhanTu_interchange)
print(f"Danh sách sau khi sắp xếp bằng Interchange Sort: {PhanTu_interchange}")

# Sắp xếp bằng Bubble Sort
bubble_sort(PhanTu_bubble)
print(f"Danh sách sau khi sắp xếp bằng Bubble Sort: {PhanTu_bubble}")

Danh sách sau khi sắp xếp bằng Interchange Sort: [1, 2, 3, 5, 5, 8, 9, 10]
Danh sách sau khi sắp xếp bằng Bubble Sort: [1, 2, 3, 5, 5, 8, 9, 10]


In [1]:
print("Bài 13")

Bài 13


In [ ]:
def sequential_search(arr, x):
    for i in range(len(arr)):
        if arr[i] == x:
            return i
    return -1

def binary_search(arr, x):
    left = 0
    right = len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == x:
            return mid
        elif arr[mid] < x:
            left = mid + 1
        else:
            right = mid - 1
    return -1

# Nhập danh sách các số nguyên từ người dùng
DaySo = input("Nhập một danh sách các số nguyên: ")
PhanTu = list(map(int, DaySo.split(',')))

# Nhập số cần tìm
x = int(input("Nhập số cần tìm: "))

# Tìm kiếm tuần tự
index_seq = sequential_search(PhanTu, x)
if index_seq != -1:
    print(f"Số {x} được tìm thấy tại vị trí {index_seq} bằng tìm kiếm tuần tự.")
else:
    print(f"Số {x} không có trong danh sách theo tìm kiếm tuần tự.")

# Sắp xếp danh sách trước khi thực hiện tìm kiếm nhị phân
PhanTu.sort()

# Tìm kiếm nhị phân
index_bin = binary_search(PhanTu, x)
if index_bin != -1:
    print(f"Số {x} được tìm thấy tại vị trí {index_bin} trong danh sách đã sắp xếp bằng tìm kiếm nhị phân.")
else:
    print(f"Số {x} không có trong danh sách đã sắp xếp theo tìm kiếm nhị phân.")


In [2]:
print("Bài 14")

Bài 14


In [18]:
alphabet=input("Nhập dãy alphabet:") #Nhập A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z vào
phanTu=alphabet.split(',')
def column_to_number(column):
    result = 0
    for char in column:
        value = phanTu.index(char) + 1
        result = result * 26 + value
    return result

def number_to_column(number):
    result = ""
    while number > 0:
        number -= 1
        du = number % 26
        char = phanTu[du]  # Chuyển đổi phần dư thành ký tự
        result = char + result  # Thêm ký tự vào kết quả
        number //= 26
    return result

# Nhập chuỗi cột từ người dùng
column = input("Nhập ký tự cột: ")
to_number = column_to_number(column)
print(f"Ký tự cột '{column}' tương ứng với số {to_number}")

# Nhập số cột từ người dùng
number = int(input("Nhập số cột: "))
to_column = number_to_column(number)
print(f"Số {number} tương ứng với ký tự cột '{to_column}'")


Ký tự cột 'Z' tương ứng với số 26
Số 12 tương ứng với ký tự cột 'L'


In [13]:
print("Bài 15")

Bài 15


In [15]:
import numpy as np

# Nhập số nguyên dương n từ người dùng
n = int(input("Nhập số nguyên dương n: "))

# Tạo ma trận đơn vị cấp n
matrix = np.eye(n)

# Xuất ma trận đơn vị
print("Ma trận đơn vị cấp", n, "là:")
print(matrix)


Ma trận đơn vị cấp 4 là:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
