In [18]:
import numpy as np

In [19]:
#Bài 1
adj_matrix = np.array([
    [0,0,1,1,1,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1],
    [1,0,0,0,0,0,0,1,0,0],
    [1,0,0,0,1,0,0,1,0,0],
    [1,0,0,1,0,0,0,0,1,1],
    [1,0,0,0,0,0,1,0,1,0],
    [0,0,0,0,0,1,0,0,0,0],
    [0,0,1,1,0,0,0,0,0,1],
    [0,1,0,1,1,0,0,0,0,1],
    [0,1,0,0,1,0,0,1,1,0]
])
print("Ma trận kề")
print(adj_matrix)

Ma trận kề
[[0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1]
 [1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 1]
 [0 1 0 1 1 0 0 0 0 1]
 [0 1 0 0 1 0 0 1 1 0]]


In [20]:
hang, cot = adj_matrix.shape
print(f"Số hàng: {hang}")
print(f"Số cột: {cot}")

Số hàng: 10
Số cột: 10


In [22]:
def bfs_search(adj_matrix,node):
    visited=[]
    bfs=[]
    bfs.append(node)
    visited.append(node)
    for x in bfs:
        for i in range(cot):
            if adj_matrix[x-1,i] == 1 and (i+1) not in visited:
                bfs.append(i+1)
                visited.append(i+1)
        if len(bfs) == cot:
            break
    return bfs

In [23]:
b = int(input("Nhập đỉnh bắt đầu để duyệt BFS: "))
bfs_result = bfs_search(adj_matrix, b)
print(bfs_result)

[5, 1, 4, 9, 10, 3, 6, 8, 2, 7]


In [24]:
adj_list={
    '1':['3','4','5','6'],
    '2':['9','10'],
    '3':['1','8'],
    '4':['1','5','8'],
    '5':['1','4','9','10'],
    '6':['1','7','9'],
    '7':['6'],
    '8':['3','4','10'],
    '9':['2','5','6','10'],
    '10':['2','5','8','9']
}
print(adj_list)

{'1': ['3', '4', '5', '6'], '2': ['9', '10'], '3': ['1', '8'], '4': ['1', '5', '8'], '5': ['1', '4', '9', '10'], '6': ['1', '7', '9'], '7': ['6'], '8': ['3', '4', '10'], '9': ['2', '5', '6', '10'], '10': ['2', '5', '8', '9']}


In [38]:
visited=[]
def dfs_search(adj_list, visited, node):
    if node not in visited:
        print(node)
        visited.append(node)
        for phantu in adj_list[node]:
            dfs_search(adj_list, visited, phantu)

In [34]:
dfs_search(adj_list, visited, '7')


7
6
1
3
8
4
5
9
2
10


In [ ]:
#Bài 2
adj_matrix = np.array([
    [0,1,1,1,0,0,0],
    [0,0,0,0,1,0,0],
    [0,0,0,0,0,1,0],
    [0,0,1,0,1,0,1],
    [0,0,0,0,0,0,1],
    [0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0]
])
print("Ma trận kề")
print(adj_matrix)

Ma trận kề
[[0 1 1 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]


In [ ]:
hang, cot = adj_matrix.shape
print(f"Số hàng: {hang}")
print(f"Số cột: {cot}")

Số hàng: 7
Số cột: 7


In [ ]:
b = int(input("Nhập đỉnh bắt đầu để duyệt BFS: "))
bfs_result = bfs_search(adj_matrix, b)
print(bfs_result)

[1, 2, 3, 4, 5, 6, 7]


In [35]:
adj_list={
    '1':['2','3','4'],
    '2':['5'],
    '3':['6'],
    '4':['3','5','7'],
    '5':['7'],
    '6':['7'],
    '7':[]
}
print(adj_list)

{'1': ['2', '3', '4'], '2': ['5'], '3': ['6'], '4': ['3', '5', '7'], '5': ['7'], '6': ['7'], '7': []}


In [39]:
dfs_search(adj_list, visited, '4')

4
3
6
7
5


In [24]:
import numpy as np
graph1 = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #S
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], #A
    [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0], #B
    [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], #C
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #D
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #E
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #F
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #G
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0], #H
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1], #I
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], #J
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], #K
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], #L
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0] #M
])

In [25]:
ver_list = ['S', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M']
ver_dict = {
    'S':0,
    'A':1,
    'B':2,
    'C':3,
    'D':4,
    'E':5,
    'F':6,
    'G':7,
    'H':8,
    'I':9,
    'J':10,
    'K':11,
    'L':12,
    'M':13,
}

In [26]:
def bfs_search(graph1,start,end):
    node_start=ver_dict[start]
    node_end=ver_dict[end]
    visited=[node_start]
    bfs=[node_start]
    r, c = graph1.shape
    for x in bfs:
        for j in range(c):
            if graph1[x,j] == 1 and j not in visited:
                visited.append(j)
                bfs.append(j)
                if j == node_end:
                    break
        if bfs[len(bfs)- 1] == node_end:
            break
    return bfs

In [27]:
bfs_result = bfs_search(graph1,'A','F')
for x in bfs_result:
    print(ver_list[x])

A
S
D
E
B
C
F


In [28]:
adj_list={
    'S':['A','B','C'],
    'A':['S','D','E'],
    'B':['S','F','G'],
    'C':['S','H'],
    'D':['A'],
    'E':['A'],
    'F':['B'],
    'G':['B'],
    'H':['C','I','J'],
    'I':['H','K','L','M'],
    'J':['H'],
    'K':['I'],
    'L':['I'],
    'M':['I']
}

In [29]:
visited=[]
def dfs_search(adj_list, visited, start, end):
    if start not in visited:
        print(start)
        visited.append(start)
        if start == end:
            return True
        for neighbor in adj_list[start]:
            if dfs_search(adj_list, visited, neighbor, end):
                return True
    return False

In [30]:
dfs_result = dfs_search(adj_list, visited, 'S', 'G')

S
A
D
E
B
F
G


In [40]:
wgraph = {
    'S': [('A', 3), ('B', 6), ('C', 5)],
    'A': [('D', 9), ('E', 8)],
    'B': [('G', 12), ('F', 14)],
    'C': [('H', 7)],
    'H': [('I', 5), ('J', 6)],
    'I': [('K', 1), ('L', 10), ('M', 2)],
    'J': [], 'D': [], 'E': [], 'F': [], 'G': [], 'K': [], 'L': [], 'M': []
}

In [41]:
import heapq
from collections import deque, defaultdict
def best_first_search(wgraph, start):
    pqueue = [(0, start, [start])]
    visited = set()
    result_order = []

    while pqueue:
        pqueue.sort()  
        weight, vertex, path = pqueue.pop(0)  
        if vertex in visited:
            continue
        visited.add(vertex)
        result_order.append(vertex)

        for neighbor, weight in wgraph[vertex]:
            if neighbor not in visited:
                pqueue.append((weight, neighbor, path + [neighbor]))

    return result_order

In [42]:
bestfs_result = best_first_search(wgraph,'S')
print(bestfs_result)

['S', 'A', 'C', 'B', 'H', 'I', 'K', 'M', 'J', 'E', 'D', 'L', 'G', 'F']
