In [1]:
print("Bài 01")

Bài 01


In [1]:
suits=input("Nhập thuộc tính bài:")
suit=suits.split(',')
print("List suits sau khi nhập từ người dùng:", suit)

values=input("Nhập giá trị bài:")
value=values.split(',')
print("List values sau khi nhập từ người dùng:", value)

for i in value:
	for j in suit:
		print(f"{i} of {j}")	

List suits sau khi nhập từ người dùng: ['Hearts', 'Diamonds', 'Clubs', 'Spades']
List values sau khi nhập từ người dùng: ['Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King', 'Ace']
Two of Hearts
Two of Diamonds
Two of Clubs
Two of Spades
Three of Hearts
Three of Diamonds
Three of Clubs
Three of Spades
Four of Hearts
Four of Diamonds
Four of Clubs
Four of Spades
Five of Hearts
Five of Diamonds
Five of Clubs
Five of Spades
Six of Hearts
Six of Diamonds
Six of Clubs
Six of Spades
Seven of Hearts
Seven of Diamonds
Seven of Clubs
Seven of Spades
Eight of Hearts
Eight of Diamonds
Eight of Clubs
Eight of Spades
Nine of Hearts
Nine of Diamonds
Nine of Clubs
Nine of Spades
Ten of Hearts
Ten of Diamonds
Ten of Clubs
Ten of Spades
Jack of Hearts
Jack of Diamonds
Jack of Clubs
Jack of Spades
Queen of Hearts
Queen of Diamonds
Queen of Clubs
Queen of Spades
King of Hearts
King of Diamonds
King of Clubs
King of Spades
Ace of Hearts
Ace of Diamonds
Ace of C

In [2]:
print("Bài 2")

Bài 2


In [10]:
DayKiTu = input("Nhập dãy kí tự: ")
PhanTu=DayKiTu.split(',')
n = int(input("Nhập số hàng: "))
m = int(input("Nhập số cột: "))

matrix = [PhanTu[i:i+m] for i in range(0, len(PhanTu), m)]
numItems = len(PhanTu)


frequency_dict = {}
for row in matrix:
    for item in row:
        if item in frequency_dict:
            frequency_dict[item] += 1
        else:
            frequency_dict[item] = 1


print("Ma trận:")
for row in matrix:
    print(row)

print()

print(f"Số phần tử trong list: {numItems}")


print("Tần số xuất hiện của từng giá trị:")
for key, value in frequency_dict.items():
    print(f"{key}: {value}")



Ma trận:
['M', 'M', 'M', 'A', 'H', 'M', 'S', 'M', 'H', 'M']
['S', 'M', 'M', 'M', 'M', 'A', 'M', 'M', 'A', 'M']
['M', 'M', 'H', 'M', 'M', 'M', 'H', 'M', 'H', 'M']
['A', 'M', 'M', 'M', 'H', 'M', 'M', 'M', 'M', 'M']

Số phần tử trong list: 40
Tần số xuất hiện của từng giá trị:
M: 28
A: 4
H: 6
S: 2


In [1]:
print("Bài 3")

Bài 3


In [12]:
width = int(input("Nhập chiều rộng:")) 
length = int(input("Nhập chiều dài:")) 

for i in range(width):
        print('*' * length)


***
***
***
***


In [4]:
print("Bài 4")

Bài 4


In [13]:
height = int(input("Nhập chiều cao:"))
for i in range(1, height + 1):
    if i == 1 or i == height: 
        print('*' * i)
    else: #Nếu i == 2 trở lên đến height - 1
        print('*' + ' ' * (i - 2) + '*') 

*
**
* *
*  *
*   *
*    *
*     *
*      *
*       *
**********


In [6]:
print("Bài 5")

Bài 5


In [14]:
def FindFibonacci(n):
    fibo = [0, 1]
    while len(fibo) < n:
        next_fibo = fibo[-1] + fibo[-2]
        fibo.append(next_fibo)
    return fibo

def FindNumberFibonacci(n):
    fibo = [0, 1]
    for i in range(2, n):
        next_fibo = fibo[-1] + fibo[-2]
        fibo.append(next_fibo)
    if n > 0:
        return fibo[n - 1] 
    else: print("Không có giá trị Fibonacci cho n <= 0")

n = int(input("Nhập n:"))
print(f"Dãy số fibonacci như sau:", FindFibonacci(n))
print(f"Giá trị Fibonacci thứ {n} là:", FindNumberFibonacci(n))


Dãy số fibonacci như sau: [0, 1, 1, 2, 3, 5, 8, 13, 21]
Giá trị Fibonacci thứ 9 là: 21


In [8]:
print("Bài 6")

Bài 6


In [1]:
import numpy as np

def create_random_array(n):
    if n % 5 == 0 and n > 20:
        return np.random.randint(0, 100, n)
    else:
        print("n không chia hết cho 5 hoặc n không lớn hơn 20")
        return None #None == Null trong python

def print_array(arr):
    # Xuất mảng
    print("Mảng 2 chiều:")
    print(arr)

def reshape_array(arr):
    return arr.reshape(-1, cot)

def print_array_info(arr):
    print("---Info---")
    print("Shape:", arr.shape)
    print("Number of dimensions:", arr.ndim)
    print("Data type:", arr.dtype)
    print("Size of each element (in bytes):", arr.itemsize)
    print("Total number of elements:", arr.size)

def count_occurrences(arr_2d, x):
    return np.count_nonzero(arr_2d == x)

def array_sum(arr1, arr2):
    return np.add(arr1, arr2)

def array_product(arr1, arr2):
    return np.multiply(arr1, arr2)

# Kiểm tra các hàm
n = int(input("Nhập n:"))
a = create_random_array(n)
if a is not None:
    print(f"Mảng 1 chiều: {a}")
    cot = int(input("Nhập số cột:"))
    print()
    mang2chieu = reshape_array(a)
    print_array(mang2chieu)
    print()
    print_array_info(mang2chieu)
    x = int(input("Nhập số cần tìm:"))
    print()
    print(f"Số lần xuất hiện của giá trị {x} trong mảng 2 chiều:", count_occurrences(mang2chieu, x))
    a1 = np.random.randint(0, 100, mang2chieu.shape)
    a2 = np.random.randint(0, 100, mang2chieu.shape)
    print()
    print("Tổng của hai mảng:")
    print(array_sum(a1, a2))
    print()
    print("Tích của hai mảng:")
    print(array_product(a1, a2))


Mảng 1 chiều: [31 30 74 18 87 40 11 35 41 59 35 43 57 97 17  1 34 38 48  4 80 68 62  8
 77]

Mảng 2 chiều:
[[31 30 74 18 87]
 [40 11 35 41 59]
 [35 43 57 97 17]
 [ 1 34 38 48  4]
 [80 68 62  8 77]]

---Info---
Shape: (5, 5)
Number of dimensions: 2
Data type: int32
Size of each element (in bytes): 4
Total number of elements: 25

Số lần xuất hiện của giá trị 25 trong mảng 2 chiều: 0

Tổng của hai mảng:
[[ 51 145 121  30 108]
 [ 80  98  82  70 175]
 [125  62  64 123 107]
 [ 91 133 181 117  82]
 [108 161  47 115  96]]

Tích của hai mảng:
[[ 560 5046 2328  176 2835]
 [1311 1440 1281    0 7584]
 [2574  936  988 2376 2752]
 [ 178 3870 8170 3380 1645]
 [1472 6348  532 1584 2279]]
